### ISSUE TITLE
<mobile:mobile></mobile:mobile>

### ISSUE THREAD

**Issue by rockymontana** [ThePixelDeveloper/Sitemap#10]
It'd be nice to have an option to handle mobile page data as well.

**Comment by ThePixelDeveloper** [comment]
Should be easier to add now that I've updated the library structure. Will take of this soon :+1:

**Comment by rockymontana** [comment]
Far out man!

**Comment by ThePixelDeveloper** [comment]
Released in 4.1

ty ty. 

PS. Sorry it took longer than I said :speak_no_evil:

**Comment by rockymontana** [comment]
But now its here! Thanks a bunch!

Med vänlig hälsning, 
Jonas Erlandsson
