### ISSUE TITLE
Missing xmlns:image even \Image sub-element was used in sitemap

### ISSUE THREAD

**Issue by fruit** [ThePixelDeveloper/Sitemap#33]
Hi there!

Maybe I'm wrong... here is an [example](http://pastebin.com/XcHKm7kH) which generates 2 `<url>` tags with additional `Image` and `Link` parts. The resulting XML does not contains an expected namespaces `xmlns:xhtml` and `xmlns:image`.

But if you change the order of adding (`addUrl`) urls to `Urlset`:

``` php
$urlSet->addUrl($urlB);
$urlSet->addUrl($urlA);
```

All will be fine, the missing namespaces appears in the output file.

**Comment by ThePixelDeveloper** [comment]
Thanks for the report, going to take a look at this further.

**Comment by tmihalik** [comment]
+1

**Comment by Dicebar** [comment]
+1
