### ISSUE TITLE
publication_date in news sitemap is not compatible with sitemap spec

### ISSUE THREAD

**Issue by shashikreddy** [ThePixelDeveloper/Sitemap#39]
Currently publication date is formatted using `DATE_ISO8601` which is not compatible with ISO-8601.
It should use `DATE_ATOM` or `DateTime::ATOM` to format date to comply with sitemap spec 
https://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd
https://www.google.com/schemas/sitemap-news/0.9/sitemap-news.xsd

**Comment by ThePixelDeveloper** [comment]
Merged into master. Preparing for release.
