### ISSUE TITLE
Add installation instruction

### ISSUE THREAD

**Issue by caztial** [ThePixelDeveloper/Sitemap#52]
Try to add installation instruction for novice users. thanks :)

**Comment by ThePixelDeveloper** [comment]
Where are you stuck, specifically?

**Comment by jasomdotnet** [comment]
For example with the code in "Basic Usage" I got 

```
https://www.salonprepsy.sk/ikonky2010-05-29T01:17:35+00:00monthly0.5
```
No XML document created. I don't know what to do. No tutorial online, no better code sample. Typical documentation made by geek which sucks :D

**Comment by jasomdotnet** [comment]
For example with the code in "Basic Usage" I got

```
https://www.example.com/my-url2010-05-29T01:17:35+00:00monthly0.5
```

No XML document created. I don't know what to do. No tutorial online, no better code sample. Typical documentation made by geek which sucks :D
