### ISSUE TITLE
Move packagist source to github

### ISSUE THREAD

**Issue by bernhard-efler** [ThePixelDeveloper/Sitemap#55]
Hi!

the current registered source on packagist has devkit.net as source, but at the moment it is offline which breaks a lot of projects.
The source is already on github, so it would be great to change packagist so there is a better reliability.

https://packagist.org/packages/thepixeldeveloper/sitemap

**Comment by gsdevme** [comment]
Yeah would be great if it could be Gitlab or Github.. one of the major hosting solutions which be much preferred so when there is an outage its really clear. 

Im not sure what http://www.devkit.net/ even is..

**Comment by NeilMasters** [comment]
I agree with both points.

For those who need to get your builds going again forking the repo is your solution.

**Comment by ThePixelDeveloper** [comment]
Updated. I was going to host my own GitLab instance to use a nicer CI solution, but it appears I got some adjustments to make. Reverted until pending more investment.

**Comment by curry684** [comment]
If you have your own master code on GitLab you can still then use CI to mirror to GitHub on successful builds to keep it reliable for users.
