### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by nucreativa** [ThePixelDeveloper/Sitemap#56]
Hi, when i try to install this, composer get stuck. When i do `composer -vvv`, it got stuck when `git remote set-url origin 'https://www.devkit.net/thepixeldeveloper/sitemap.git' && git remote update --prune origin`. Can you switch git repo from devkit.net to github? thanks

**Comment by mikerockett** [comment]
Related: #55

**Comment by ThePixelDeveloper** [comment]
It should have updated, if you're still having issues then let me know.

**Comment by nucreativa** [comment]
it works now. thanks
