### ISSUE TITLE
Feature Request: allow adding comments

### ISSUE THREAD

**Issue by holtkamp** [ThePixelDeveloper/Sitemap#59]
Basically the same as https://github.com/ThePixelDeveloper/Sitemap/issues/32, but now for XML comments. 

In some cases it is usefull to inject comments, for example about the time and memory it took to generate a sitemap. This can currently be done using a custom processing instruction, but a comment is a more elegant approach...

```php
$output->addProcessingInstruction('comment', sprintf('generationTime: %f seconds', $generationTime));
```

If agreed that this is a reasonable request, I can try to come up with a PR.

**Comment by ThePixelDeveloper** [comment]
Hi.

You mind going into why you'd want this information in the output? I'd normally wrap the process of generating the XML file with something that collects the metrics to another output format.

**Comment by holtkamp** [comment]
Well, mainly for two reasons:

- we got 3 caching layers in front of the application server, the generation timestamp allows me to verify whether al these caching layers work properly
- some of the generated sitemaps are "huge" and require a significant amount of memory and time to generate, so some information about this is nice to be able to tune the memory assigned to the used application server containers (Heroku)

Of course this information can also be logged, but putting them in a comment makes it a bit easier to access.

**Comment by ThePixelDeveloper** [comment]
@holtkamp Sorry for taking a long time to respond to your comments.

I wasn't originally a fan of the idea, but I've come around to agreeing with you. You'll see a change come out soon. Will keep you updated.

Do you have any other ideas for the library?

**Comment by holtkamp** [comment]
>Sorry for taking a long time to respond to your comments.

No worries, I know time seems always scarce! Thanks for adopting the idea. 

>Do you have any other ideas for the library?

No, currently not, satisfies all posed needs... When I encounter something, will let you know!
